### ISSUE TITLE
Timeout error

### ISSUE THREAD

**Issue by kmuthukrishnan** [algolia/algolia-firebase-nodejs#4]
Hi @algolia, 

I have a relatively large node of data (9000 records) that I would like move from firebase to algolia. This project worked for me in the past. However I am now hitting a timeout error as below:

```
C:\Users\krithika\Desktop\NATIVESCRIPT\Firebase\algolia-firebase-nodejs>node importFirebaseToAlgolia

C:\Users\krithika\Desktop\NATIVESCRIPT\Firebase\algolia-firebase-nodejs\importFirebaseToAlgolia.js:43
      throw err;
      ^
AlgoliaSearchRequestTimeoutError: Request timedout before getting a response
    at Timeout.timeout [as _onTimeout] (C:\Users\krithika\Desktop\NATIVESCRIPT\Firebase\algolia-firebase-nodejs\node_modules\algoliasearch\src\server\builds\node.js:234:14)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
```

The error does not happen with a smaller node like 20 items. Please suggest what I could do. Thanks

**Comment by Haroenv** [comment]
You should chunk when you push to Algolia, depending on your location etc. Something like 200/1000 records per API call is good

You can split up the objects before here: https://github.com/algolia/algolia-firebase-nodejs/blob/master/importFirebaseToAlgolia.js#L36

**Comment by kmuthukrishnan** [comment]
Thanks @ algolia,
Will try. Also instead of initializing the index every time can i push to an existing index? Please let me know how I could do that.

**Comment by Haroenv** [comment]
`initIndex` can take the name of an existing index, it will simply append to that index, or create it if needed

**Comment by Haroenv** [comment]
Feel free to reopen if you need more guidance
